### ISSUE TITLE
How is MDAnalysis neighbor search edited?

### ISSUE THREAD

**Issue by bdice** [rsdefever/GenStrIde#1]
Hi, I attended a talk at AIChE by Prof. Sarupria about this work. Could you explain how and why you included a custom version of MDAnalysis neighbor finding in this work? There isn't a commit history so it's tough to identify why this was needed for your study.

Context: I'm a core developer of the [freud library](https://freud.readthedocs.io/en/stable/) for simulation analysis and have started some conversations with MDAnalysis developers about collaborating to improve neighbor finding algorithms in our respective libraries. In some cases, freud is faster than MDAnalysis, so I'm interested in determining whether your primary reason to edit MDAnalysis's routines was performance, correctness, or other factors.

**Comment by rsdefever** [comment]
Hello! 

Apologies for the lack of commit history. 

We need access to the x,y, and z components of the distance (dx, dy, and dz) between two points rather than just the distance between the two points, r. MDAnalysis did not offer the ability to get that information from the neighbor search. If I remember correctly, you could get the list of neighbors and the overall distance between each pair of neighbors, but not dx,dy,dz. The modifications made here were just adding a couple of functions (for example, the get_dx() function) to allow the dx,dy,dz info to be passed back up into python. 

IMHO: the first step in an overwhelming amount of trajectory analysis is calculating (dx,dy,dz). If these sorts of tools are going to offer the flexibility for any kind of custom analysis, fast and flexible access that info is crucial.

**Comment by bdice** [comment]
@rsdefever Thanks for the reply! That makes sense. I’ve faced similar challenges needing the full vector while developing the freud library. I appreciate the info, I’ll close this issue.
